### ISSUE TITLE
IJB-A test problem

### ISSUE THREAD

**Issue by stormyoung** [penincillin/DREAM#53]
Hello，Thank you for your great work!
I get a problem when I test IJB-A using your method.
First I download IJB-A provided by your link. and I run bash eval_ijba.sh, the problem occurs.

FileNotFoundError: [Errno 2] No such file or directory: '/mnt/SSD/rongyu/data/IJBA/align_image_11/ijb_a_11_align_split1/frame/31593_01800.png'

**Comment by svena33** [comment]
Hi, I don't know if you solved it but for future users strugling with the same issue I made the following fix.

The problem occurs because the 'data/IJBA/align_image_xx/ijb_a_11_align_splitx/frame_list.txt' refers to the image locations based on the author's file system. Assuming your data is in $DREAM/data/IJBA/align_image.... , this can be fixed in the following way.

Original:
'/mnt/SSD/rongyu/data/IJBA/align_image_11/ijb_a_11_align_split1/frame/31593_01800.png'
Fix:
'../../data/IJBA/align_image_11/ijb_a_11_align_split1/frame/31593_01800.png' 

Simply fix: 

$DREAM/src/IJBA/selfDefine.py 

from:

```
def load_imgs(img_dir, image_list_file):
    imgs = list()
    with open(image_list_file, 'r') as imf:
        for line in imf:
            record = line.strip().split()
            img_path, yaw = os.path.join(img_dir,record[0]), float(record[1])
            imgs.append((img_path, yaw))
    return imgs
```

to:

```
def fix_folder(oldPath):
    oldPath = oldPath
    temppath = os.path.normpath(oldPath).split(os.path.sep)[3:]
    temppath[0:1]=['..','..']
    newPath = os.path.join(*temppath)
    return newPath

def load_imgs(img_dir, image_list_file):
    imgs = list()
    with open(image_list_file, 'r') as imf:
        for line in imf:
            record = line.strip().split()
            img_path, yaw = os.path.join(img_dir,record[0]), float(record[1])
            img_path = fix_folder(img_path) ##fix path
            imgs.append((img_path, yaw))
    return imgs

```

Hope this helps!
